"""add user.password_hash

Revision ID: 4dbf96ff6403
Revises: 279bdaaeafe1
Create Date: 2026-06-23 12:52:18.087039

"""
from typing import Sequence, Union
from passlib.context import CryptContext
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbf96ff6403'
down_revision: Union[str, Sequence[str], None] = '279bdaaeafe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


pwd = CryptContext(schemes=["bcrypt"], deprecated="auto")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###
    default_hash = pwd.hash("password123")
    op.execute(
        sa.text("UPDATE users SET password_hash = :h").bindparams(h=default_hash)
    )
    op.alter_column('users', 'password_hash', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
