"""add name unique

Revision ID: 556979572e22
Revises: 4dbf96ff6403
Create Date: 2026-06-23 13:29:45.009154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556979572e22'
down_revision: Union[str, Sequence[str], None] = '4dbf96ff6403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ug_users_name", 'users', type_='unique')
    # ### end Alembic commands ###
